# Questão 2.2


## 2. 
Usando o esquema numérico de Crank-Nicolson resolve o problema mixto para a equa ̧c ̃ao paraxial no dominio $Ω = {(x, z)|x ∈ [0, 3000], z ∈ [0, 500]}$ de forma seguinte:

- a equação:

$$iu_x + bu_{zz} + Vu = 0$$

- os coeficientes:

$$b
 = 5$$ 

$$V (z) = exp(iz/4) exp \frac{
(z − 250)2}
{1500} $$


- as condiçoes de contorno:
 $$u(x, 0) = u(x, L) =
  0$$
onde $$L = 
500$$ ,
- a condi ̧c ̃ao inicial:

$$u(0, z) = u_0(z) = exp \frac{ 
(z − 250)^2}
{30000} $$
.

Dica: pode usar passos ∆x = 5, ∆z = 1.

Primeiramente vamos definir o stencil 

In [2]:
! pip install numpy scipy 

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 1.5 MB/s  0:00:10m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 1.0 MB/s  0:00:32m0:00:0100:010m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [scipy]32m1/2 [scipy]


In [ ]:

import numpy as np
from scipy.sparse import diags, dia_matrix


x_max = 3000
z_max = 500

delta_x = 5 
delta_z = 1
n_x = int(x_max/delta_x) # Número de pontos do stenccil em x
n_z = int(z_max/delta_z) # Número de pontos do stenccil em y
x = np.linspace(0, x_max, n_x)
z = np.linspace(0, z_max, n_z)

X, Z = np.meshgrid(x,z)

def V(z):
    return exp()



No nosso esquema, temos uma recorrencia da seguinte forma:

$$A r_{n+1}  = B r_{n}$$

Onde $r_n$ representa o vetor:


$$r_n = 
\begin{pmatrix} 
u(x_n, z_0) = u_{n,0}\\
u(x_n, z_1) = u_{n,1}\\
\vdots \\ 
u(x_n, z_i) = u_{n,i}\\
\vdots \\
\end{pmatrix}
$$


$$x_n = x_0 + n*\Delta x$$
$$z_i = z_0 + i*\Delta z $$


Como o potencial não depende de x, e como a matriz de propragação $ A^{-1} C $ ( sabemos que $A$ tem inversa) apresentam dependencia de $x$ ( e consequentemente $n$ ) apenas devido ao potencial, então podemos concluir que a matriz é  a mesma para todo $n$. Portanto, basta inverter a e calcular o produto $A^{-1}C$ uma vez


In [16]:

b = np.ones(99)
c = np.ones(98)
A = diags([c,b,a,b,c], [-2,-1,0,1,2], shape=(10,10), format='dia')
a = np.ones(10)*0
b = np.ones(9)*1
c = np.ones(8)*2
A = diags([c,b,a,b,c], [-2,-1,0,1,2], shape=(10,10), format='dia')

print(A.toarray())


[[0. 1. 2. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 2. 0. 0. 0. 0. 0. 0.]
 [2. 1. 0. 1. 2. 0. 0. 0. 0. 0.]
 [0. 2. 1. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 2. 1. 0. 1. 2. 0. 0. 0.]
 [0. 0. 0. 2. 1. 0. 1. 2. 0. 0.]
 [0. 0. 0. 0. 2. 1. 0. 1. 2. 0.]
 [0. 0. 0. 0. 0. 2. 1. 0. 1. 2.]
 [0. 0. 0. 0. 0. 0. 2. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 2. 1. 0.]]
